# Generated by Django 5.1.7 on 2025-07-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turista', '0002_lugar_agendaviaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaViaje',
        ),
    ]
