# Generated by Django 5.1.7 on 2025-07-25 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turista', '0003_delete_agendaviaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaViajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_planificada', models.DateField()),
                ('es_favorito', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turista.lugarturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'lugar')},
            },
        ),
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
